### ISSUE TITLE
convert mp4 video to avi

### ISSUE THREAD

**Issue by miladr0** [brarcher/video-transcoder#131]
hi
could this library do that?

**Comment by licaon-kter** [comment]
Why?

**Comment by brarcher** [comment]
I do not think that the app currently has support for AVI, but ffmpeg (used by the app) does. The support would just need to be added.

**Comment by licaon-kter** [comment]
@miladr0 Why AVI format, what's the purpose? Why not MKV or MP4 or any `modern` container?

**Comment by miladr0** [comment]
@licaon-kter i'm just interest this format and want add it as an option for convert.

**Comment by brarcher** [comment]
I looked into it, and the [FFmpeg build](https://github.com/brarcher/ffmpeg-android) I'm using does not currently have libxvid support. That would need to be added first. FFmpeg does have built-in support for AVI but the quality is not as good as libxvid for lower bitrates ([source](https://trac.ffmpeg.org/wiki/Encode/MPEG-4)). If AVI support were to be added to Video Transcoder I'd prefer it be with libxvid.

If someone were interested in adding libxvid support to the [ffmpeg-android](https://github.com/brarcher/ffmpeg-android) fork I use, it would make adding support to the app simpler. Otherwise, it may be some time before I can get to it.
