### ISSUE TITLE
Add OPUS as audio container

### ISSUE THREAD

**Issue by nulledone** [brarcher/video-transcoder#37]

**Comment by brarcher** [comment]
I see that the FFmpeg build used by the application does support Opus. Are you familiar with what codecs are supported in that container? Adding support is easy enough, just an entry to the [MediaContainer](https://github.com/brarcher/video-transcoder/blob/master/app/src/main/java/protect/videotranscoder/media/MediaContainer.java#L13) enum and any audio codecs to the [AudioCodec](https://github.com/brarcher/video-transcoder/blob/master/app/src/main/java/protect/videotranscoder/media/AudioCodec.java#L12) enum, along with looking up the proper ffmpeg arguments. If someone were willing to track that information down and test it I could help review the pull request.

**Comment by nulledone** [comment]
Well as far as I know MKV, WEBM and MP4.

Wikipedia shows MPEG-TS addition to my mentions.

**Comment by Djfe** [comment]
.opus and .ogg as well
I'm not sure about mp4
and while ts is theoretically possible: is there a standardized mapping, yet?

**Comment by brarcher** [comment]
The version and build of FFmpeg which is being used does support the opus codec, both in an opus audio container and in the MKV video container. This support is now exposed to the UI. FFmpeg does have experimental support for mp4, but this is not being exposed as I'm not sure how well "experimental support" works.

Playing with it, I did observe that opus supports only some sample frequencies (list on [this page](https://en.wikipedia.org/wiki/Opus_(audio_format))), but presently more options than are valid are displayed. In the future the list of valid options should be shown instead of a broad list.

If there is something that I missed, let me know.
