### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by revilationer** [brarcher/video-transcoder#57]
Hi! If you need a icon for your app i can help you. You just have to write what kind of thing do you want, then i'll design it as you want!

**Comment by brarcher** [comment]
Thanks for the offer! Honestly, I'm not sure what type of icon would be best. At least something which communicates the intention of the application (transcodes video, extracts audio, etc). The icon it has now was a quick-fix so I had something. Could you suggest a few options? In addition, perhaps suggest what color scheme could be used in the application so better match the color scheme of the icon.

**Comment by revilationer** [comment]
I have some ideas that i think you will like, i am starting to design. You can check my porfolio at here: https://steemit.com/@revilationer, which sizes do you need?

**Comment by revilationer** [comment]
I have proposed a icon and logo for you;
![katman 2](https://user-images.githubusercontent.com/35149966/37790806-9723b8b6-2e18-11e8-8e89-032e612d8e68.png)
you can reach all the editable and flat files from here: https://drive.google.com/drive/folders/1H1SbAAiKJrgB-u7hbdrOdNzrnVGKxC9A
I'm waiting for your comments :)) I hope you will like it.

**Comment by licaon-kter** [comment]
@revilationer

Is this some self-assigned utopian.io task that you did in the hopes of winning some crypto-currency?

**Comment by revilationer** [comment]
@licaon-kter
Yes, thats true

**Comment by phuyuk** [comment]
But what message does this icon convey, that the app will chew up and destroy your videos? (Insult to injury, apparently it will leave crumbs, too.)  Call me crazy, but shouldn't it suggest transformation?  It could be as simple as two differently-colored - maybe red and blue - but otherwise-identical film strips, side by side, with a double-headed arrow between them (or not). Red-to-blue, or blue-to-red. Your choice. Transformation.

**Comment by revilationer** [comment]
I am waiting for the throughts of @brarcher, if he thinks like you i can redesign

**Comment by brarcher** [comment]
I appreciate the proposal, but I'm not sure I'm a fan. Though, I'm not sure what would be a better approach.

@DavidXochipilli, having developed the icons for [loyalty card keychain](https://github.com/brarcher/loyalty-card-locker/issues/151) and [gift card guard](https://github.com/brarcher/gift-card-guard/pull/37), might you give your opinion on the icon for this application?

**Comment by revilationer** [comment]
Are you have discord account? We can talk rapidly overthere

**Comment by utack** [comment]
Vinyl used a icon from flaticon
https://github.com/AdrienPoupa/VinylMusicPlayer

**Comment by phuyuk** [comment]
"... icons for loyalty card keychain and gift card guard, might you give your opinion on the icon for this application?"

Only because you asked (lol).

Gift Card Guard's icon makes no sense (to me);.Without a printed title, I wouldn't have a clue what that app did - even zoomed up, full-screen. In fact, my first visual association was Southpark's Mr Hat, but I don't imagine that was the artist's intention. If I hadn't known the title of the app, my best guess would have been an email or messaging client.

Loyalty Card Keychain's logo is more effective. Even more 'professional'. Although my first thought was "it's a chess game", it does arguably suggest 'security', which (I assume) is a core function of the product. However, I have no idea what those floating stars are supposed to represent - and if you have to explain it to me, it was a failure.

An Icon/logo that doesn't take itself too seriously (ie. cute and silly) is entirely appropriate for entertainment apps; but even then, it should (cleverly) suggest something about the product's main function. And most importantly, everyone - especially the intended consumer - should 'get it' in the first second. If minutes under magnification still doesn't reveal its meaning, then it was a marketing failure. I'm sorry to be the one to say it.

If you argue that Google and Microsoft have silly looking icons, my response will be that they are Google and Microsoft - you are not.

This Video Transcoder app is not a game. It's a utility - an important one, in my opinion. It deserves to succeed and so It deserves a professional, clean icon. Fortunately, this app's functionality is straightforward and should be easily represented in a graphic. The idea I suggested, a few posts back, was only meant to illustrate my point, that a simple, meaningful icon shouldn't be too difficult.

The graphic proposed by @revilationer has two problems, in my opinion. I'll get the first one out of the way, since it has more to do with personal taste. it's too cute. Secondly, and more importantly, while it does suggest video/film (good), it completely misses the mark on function. From that logo, I would reasonably assume that the app completely and irreversibly destroys videos. It turns them to crumbs - that's what I see in the graphic.

Having said all that, the current icon, wherever it came from, is not so bad (although it misses the mark on 'transformation'.) But if you're intent on replacing it, I suggest that you solicit 'first impressions' from people you know. Ask them to guess what the app does, based solely on the graphic.

But that's just my opinion (lol).

**Comment by phuyuk** [comment]
To all concerned:

I just read my own post and it is cruel. I'm sorry about that - it's not my nature. I foresee this app quickly developing into a polished indispensible 'product'. It deserves to be so. I've worked in film and television for 30 years, and I know what happens when preliminary and early marginal/bad concepts aren't challenged and become entrenched. A product's image shouldn't ever have to be changed, and the logo is the face of that image. Get it right the first time - it's worth it. Even if the product is open source and free, it will lead to greater community participation and wider distribution and acceptance. People are attracted to a nice logo - even if the product is crap. Sadly, the converse is not true. Image matters.

Again, I'm sorry about the harshness of my previous post.

**Comment by brarcher** [comment]
The initial motivation of this project was out of frustration. Whenever I needed to shrink or trim a video on my phone I needed to move it to my laptop first. There were applications on the Play store which would do this, but they either had ads or cost money. I don't have the play store app on my phone (only F-Droid), so I decided to see how hard it was to make an app which filled my needs.

My other applications fill small niches and are useful to me, but maybe are not that useful to others. The Loyalty card app ended up to being useful to others, so that is good. In publishing this Video Transcoding app to the Play store I did not know what kind of reception it would get. It is rather rough, but I've gotten more feedback on it and good reviews than I expected. People coming back to GitHub and asking questions or requesting features shows that there is interest. Perhaps I was not the only one frustrated with a lack of open source alternative for Android.

I'll admit that the current icon is not that good. Visual layout stuff is not my forte so I just put something there to start. As such, if there is interest in improving it, it will need to come from the community. I'm glad to see that there is interest. I am looking for a discussion about what would be a good icon and why, so that when a good solution is arrived at there is some consensus with anyone who is interested in participating. We seem to be heading in that direction. Sorry in advance if there are ruffled feathers.

> Are you have discord account?

I do not, sorry. I'd prefer to keep the discussion here, so that others will be able to also give feedback if they want.

**Comment by DavidXochipilli** [comment]
Sorry for the late reply. 
I am not using [this app](https://play.google.com/store/apps/details?id=protect.videoeditor) but I think that a new icon would be nice. I am not sure what would suit best and how to include the message that this app can format, trim and extract audio from videos.  🤔 
Maybe I will find time next month to make a sketch but I cannot promise anything.

**Comment by DavidXochipilli** [comment]
First try:
![video_transcodic](https://user-images.githubusercontent.com/29784866/40207524-44b4682a-5a35-11e8-9652-bff24548eda2.png)
What do you think?

**Comment by TacoTheDank** [comment]
eyyy thats pretty goooood

**Comment by TacoTheDank** [comment]
btw what program do you use to make these? @DavidXochipilli

**Comment by DavidXochipilli** [comment]
@TacoTheDank, I use [Adobe XD](https://www.adobe.com/xd).

**Comment by brarcher** [comment]
@DavidXochipilli, it looks nice. I had someone take a look to see if they could guess what the app did. They correctly said 'audio' and 'video' something. (:    Can you tell me what the yellow rectangle represents? Is it an envelope?

I'm not sure how to best represent that the app transforms {video, audio} -> {video, audio} without making it really complicated. FFmpeg (the tool that the app uses) does not seem to have an icon, and Libav (a fork of FFmpeg) has an icon but it does not mean anything to me:

![image](https://user-images.githubusercontent.com/5264535/40395697-50fecce0-5df7-11e8-8cba-42fe3b39ed49.png)

There is another app which does something similar [here](https://play.google.com/store/apps/details?id=com.keerby.formatfactory). It has a gear in the icon, which to me implies processing data. Is that a good idea?

![image](https://user-images.githubusercontent.com/5264535/40395910-5b29f84c-5df8-11e8-9b0e-f6e0753c0e79.png)

Would having a gear or something make more sense than the envelope? Or does the envelope make more sense? What do you think?

**Comment by DavidXochipilli** [comment]
The yellow part is an open folder / box, not an envelope. I was thinking about the aspect that the app can handle video and audio so I put both into the box.

Anyway, I made a second icon which looks more like your green example:

![video_transcodic_ii](https://user-images.githubusercontent.com/29784866/40589731-0d36cc4c-61f3-11e8-9902-fcd61f742826.png)

What do you think?

**Comment by brarcher** [comment]
I like it (:

What color scheme might you suggest in the app with this icon? Right now the colors are blue/purple with an orange as an accent.

Like the icon you created for [Loyalty Card Keychain](https://github.com/brarcher/loyalty-card-locker/issues/151#issuecomment-354358820), I would need icons of the following sizes for the app icon:
48 × 48
72 × 72
96 × 96
144 × 144
192 × 192

As well as the following for the Play store:
512 x 512 [32-bit PNG (with alpha)]

I might also like some larger versions, in case the app gets more complex and I add a first start wizard. Those sizes would be:
192 × 192
288 × 288
384 × 384
576 × 576
768 × 768

Would you also be interested in contributing a feature graphic? It would be 1024 w x 500 h, JPG or 24-bit PNG (no alpha). The current feature graphic is something I created very quickly and does not communicate much. (:

Thanks!

**Comment by DavidXochipilli** [comment]
I will prepare a ZIP with the logo and send it next week. 
Additionally, I will think about a new feature graphic.

**Comment by DavidXochipilli** [comment]
Here is the zip:

[Video_Transcoder.zip](https://github.com/brarcher/video-transcoder/files/2077858/Video_Transcoder.zip)

The icon is under the CC0 1.0 Universal license.

**Comment by DavidXochipilli** [comment]
I will send the color scheme and a feature graphic later this month.

**Comment by DavidXochipilli** [comment]
Here is the list of color codes for the application:

used in the icon
primary: D32F2F 
primary dark: F44336 

used in the UI design 
primary : EF4438 
primary dark: D32E2E

![asset](https://user-images.githubusercontent.com/29784866/41230260-6b14bb8e-6d7f-11e8-8f5a-4d1e174ed01c.png)

**Comment by brarcher** [comment]
This is great, @DavidXochipilli, thanks! 

One question, do you have a suggestion for the accent color, or is the current #ffc107 still good? 

![image](https://user-images.githubusercontent.com/5264535/41236638-9691e07c-6d5f-11e8-8e89-51b3edbf38ae.png)

**Comment by brarcher** [comment]
Great! I've pushed the new icon and color scheme. Thanks for the contribution.

When you have time for the feature graphic just let me know and I'll upload it to the Play store.

**Comment by DavidXochipilli** [comment]
@brarcher, @licaon-kter, @TacoTheDank, @betsythefc, what do you think of this feature graphic?

![google-feature-graphic](https://user-images.githubusercontent.com/29784866/44120275-2babac9e-a01c-11e8-82fd-0dd24fb6b5c8.png)

**Comment by brarcher** [comment]
I like it. The only suggestion would be to add an 'r' at the end: Video Transcoder.

**Comment by TacoTheDank** [comment]
lol video transcode, anyways nice

**Comment by DavidXochipilli** [comment]
Ups 😅 
I attached the right version for you. 
That Google Play feature graphic is under the CC0 1.0 Universal license.

[fg.zip](https://github.com/brarcher/video-transcoder/files/2299728/fg.zip)

**Comment by brarcher** [comment]
Looks good! Thanks for contributing the logo and feature graphic. I've update the Play Store with the feature graphic and it should be up soon.
