### ISSUE TITLE
Make FilePicker scroll faster for big folders

### ISSUE THREAD

**Issue by Nebukadneza** [brarcher/video-transcoder#90]
Hi,

thanks for this nice project — and the best and only usable FOSS transcoder for android :+1: .

On Android phones, people often don’t move pictures and videos around. Thus, the `Camera/DCIM`-folder (or whatever it’s called on your device), is often crowded, with thousands of pictures and (a little less) videos. Especially since videos come at the end of that list (`VID_* > IMG_*`), it’s arduous to scroll through ~8000 files to pick your most recent video.

It’d be great if this could somehow be improved. I have looked over the source quickly, and found you use the excellent NoNonsense-FilePicker. There’s an issue over at their tracker, for exactly this behavior:
https://github.com/spacecowboy/NoNonsense-FilePicker/issues/87
The suggested resolution to use https://github.com/timusus/RecyclerView-FastScroll looks quite nice IMO. If you scroll down in the FilePicker issue, you’ll find they even added this in their example code.

It’d be great if the already very useful Video-Transcoder could be made even more accessible and convenient with this addition.

Thanks and Best Regards
-Dario

**Comment by brarcher** [comment]
Interesting. I had not tried selecting a file in a very large directory, but trying that now I see that it is painfully slow and tedious to get to the bottom.

The fast scroll example you pointed me to is pretty simple. It ends up adding a scroll bar; nothing fancy but it gets the job done.

I have this change up now [here](https://github.com/brarcher/video-transcoder/pull/91), if you are interested in building it and trying it out. Otherwise, I'll test it a bit more and if I'm satisfied with it I'll push it.

**Comment by brarcher** [comment]
I've pushed the fast scrolling change. It will appear in the next release. Thanks for the suggestion.

**Comment by Nebukadneza** [comment]
Hi,

wow, that was insanely quick! Thanks a lot for your great and fast work here. I didn’t even have time to check out the change. I will still do so this evening ^_^.

Can’t wait for the next release, thanks a bunch!
-Dario

**Comment by brarcher** [comment]
> wow, that was insanely quick!

Nah, just got lucky. I saw your request when I had 20 min free and it seemed like a simple enough change which would also be rather useful. You sold the request well. (:

If you see that the fast scrolling could be improved further (or if it does not work for you), let me know.
